my_first_project/blog/urls.py
from django.urls import path

from blog.views.views import (
    get_posts,
    get_post,
    create_post,
    get_comments,
    get_comment,
    create_comment,
    PostListView,
    PostDetailView,
    CommentListView,
    CommentDetailView,
    PostCreateView, CommentCreateView, PostUpdateView, CommentUpdateView, PostDeleteView, CommentDeleteView,
)

app_name = "blog"

urlpatterns = [
    # posts
    path("posts/", get_posts, name="post_list"),
    path("posts/<int:id>", get_post, name="post_detail"),
    path("cbv-posts/", PostListView.as_view(), name="cbv_post_list"),
    path("cbv-posts/<int:id>", PostDetailView.as_view(), name="cbv_post_detail"),
    path("create-post", create_post, name="post_create"),
    path("cbv-create-post", PostCreateView.as_view(), name="cbv_post_create"),
    path("cbv-post-update/<int:id>", PostUpdateView.as_view(), name="cbv_post_update"),
    path("cbv-post-delete/<int:id>", PostDeleteView.as_view(), name="cbv_post_delete"),
    # comments
    path("create-comment", create_comment, name="comment_create"),
    path("comments/", get_comments, name="comment_list"),
    path("comments/<int:id>", get_comment, name="comment_detail"),
    path("cbv-comments/", CommentListView.as_view(), name="cbv_comment_list"),
    path(
        "cbv-comments/<int:id>", CommentDetailView.as_view(), name="cbv_comment_detail"
    ),
    path("cbv-create-comment", CommentCreateView.as_view(), name="cbv_comment_create"),
    path("cbv-update-comment/<int:id>", CommentUpdateView.as_view(), name="cbv_comment_update"),
    path("cbv-comment-delete/<int:id>", CommentDeleteView.as_view(), name="cbv_comment_delete"),
]

my_first_project/server/urls.py
from django.contrib import admin
from django.urls import path, include

from first_app.views import (
    hello_world,
    flatten_list,
    flatten_list_with_html,
    my_next_view_with_context,
    iterate_over_months,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hello_world/", hello_world),
    path("flatten_list/", flatten_list),
    path("flatten_list_html/", flatten_list_with_html),
    path("view_with_ctx/", my_next_view_with_context),
    path("months", iterate_over_months),
    path("blog/", include("blog.urls"), name="blog"),
    path("generic-blog/", include("blog.generic_urls", namespace="generic_blog"), name="generic_blog"),
]

my_first_project/blog/models.py
from django.conf.global_settings import AUTH_USER_MODEL
from django.db import models

User = AUTH_USER_MODEL

"""
Post

id: int  # dostajemy od ręki w Django
author: FK 
title: CharField
content: TextField
created_at: Datetime
updated_at: Datetime
"""


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default="Some default title")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Post by: {self.author}, created at: {self.created_at}"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Comment {self.id} by: {self.author}, for Post {self.post.title}"


class Reaction(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True, default=None)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Reaction id: {self.id}"


"""
Co zrobić:
do modelu reaction chcemy dodać widoki, templatki oraz urle które pozwolą nam lajkować posty oraz komentarze, trzeba
pamiętać, że w danym momencie możemy dodać reakcję tylko dla komentarza, lub postu. Liczba lajków powinna się wyświetlać zarówno
w detailu posta i komentarza jak i w widokach listy, tam też powinny być opcje zalajkowania danego posta i komentarza.

Pamiętajcie o tym by wyświetlać odpowiednie komunikaty dla usera w momencie, gdy wprowadził coś nie tak, czy też program
nie zadziałał jak należy
"""

my_first_project/blog/forms.py
from django import forms
from django.contrib.auth import get_user_model

from blog.models import Post, Comment

User = get_user_model()


class PostForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all())
    title = forms.CharField(max_length=100)
    content = forms.CharField()


class CommentForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all())
    post = forms.ModelChoiceField(queryset=Post.objects.all())
    content = forms.CharField()


class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={"cols": 20, "rows": 20}))

    class Meta:
        model = Post
        fields = ["title", "content"]


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["post", "content"]

my_first_project/blog/views/generic_views.py
from django.views.generic import (
    DetailView,
    View,
    CreateView,
    UpdateView,
    DeleteView,
    ListView,
)

from blog.forms import PostModelForm
from blog.models import Post


class PostGenericDetailView(DetailView):
    model = Post


class PostGenericListView(ListView):
    model = Post


class PostGenericUpdateView(UpdateView):
    model = Post
    fields = ["author", "title", "content"]


class PostGenericCreateView(CreateView):
    model = Post
    form_class = PostModelForm
    template_name = "blog/generics/create_post.html"


class PostGenericDeleteView(DeleteView):
    model = Post

my_first_project/blog/views/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views.generic import DetailView, View

from blog.forms import PostForm, CommentForm, PostModelForm, CommentModelForm
from blog.models import Post, Comment

User = get_user_model()

"""
Mając zapisane w bazie pewną pulę postów, chcemy zrobić końcówkę(url) po wejściu na który wyświetli nam się lista takich postów

Pamiętajcie o tym jak do tej pory robiliśmy widoki, a z nowych rzeczy to jak pobieraliśmy z bazy rekordy dotyczące postów, 
google i docsy django też tutaj będą na pewno w stanie pomóc
"""


def get_posts(request):
    posts = Post.objects.all()
    ctx = {"posts": posts}

    return render(request, "blog/posts.html", context=ctx)


def get_post(request, id: int):
    """
    Co chcemy zmienić: chcemy ten widok usprawnić, aby w momencie podania id po którym nie znajdujemy posta, nie wywalał się błąd,
    a user dostanie informację, że taki post nie istnieje
    """
    try:
        post = Post.objects.get(id=id)
        ctx = {"post": post}

    except Post.DoesNotExist:
        ctx = {"post_id": id}

    return render(request, "blog/post.html", context=ctx)


def get_comments(request):
    comments = Comment.objects.all()
    ctx = {"comments": comments}

    return render(request, "blog/comments.html", context=ctx)


def get_comment(request, id: int):
    try:
        comment = Comment.objects.get(id=id)
        ctx = {"comment": comment}
    except Comment.DoesNotExist:
        ctx = {"comment_id": id}

    return render(request, "blog/comment.html", context=ctx)


@login_required
def create_post(request):
    if request.method == "GET":
        form = PostModelForm()
        ctx = {"form": form}
        return render(request, "blog/create_post.html", context=ctx)
    elif request.method == "POST":
        form = PostModelForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            author = request.user
            post.author = author
            post.save()
            ctx = {"post": post, "form": form}
            return render(request, "blog/create_post.html", context=ctx)
        return render(request, "blog/create_post.html", {"form": form})


def create_comment(request):
    if request.method == "GET":
        if not request.user.is_authenticated:
            ctx = {"not_authenticated": True}
            return render(request, "blog/create_comment.html", context=ctx)
        form = CommentModelForm()
        ctx = {"form": form}
        return render(request, "blog/create_comment.html", context=ctx)
    elif request.method == "POST":
        form = CommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            author = request.user
            comment.author = author
            comment.save()
            ctx = {"comment": comment, "form": form}

            return render(request, "blog/create_comment.html", context=ctx)
        return render(request, "blog/create_comment.html", {"form": form})


class PostListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        ctx = {"posts": posts}

        return render(self.request, "blog/posts.html", context=ctx)


class PostDetailView(View):
    def get(self, request, id, *args, **kwargs):
        try:
            post = Post.objects.get(id=id)
            ctx = {"post": post}
        except Post.DoesNotExist:
            ctx = {"post_id": id}

        return render(self.request, "blog/post.html", context=ctx)


class CommentListView(View):
    def get(self, request, *args, **kwargs):
        comments = Comment.objects.all()
        ctx = {"comments": comments}

        return render(self.request, "blog/comments.html", context=ctx)


class CommentDetailView(View):
    def get(self, request, id, *args, **kwargs):
        try:
            comment = Comment.objects.get(id=id)
            ctx = {"comment": comment}
        except Comment.DoesNotExist:
            ctx = {"comment_id": id}

        return render(self.request, "blog/comment.html", context=ctx)


class PostCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = PostModelForm()
        ctx = {"form": form}

        return render(request, "blog/create_post.html", context=ctx)

    def post(self, request, *args, **kwargs):
        form = PostModelForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            author = request.user
            post.author = author
            post.save()
            ctx = {"post": post, "form": form}
            return render(request, "blog/create_post.html", context=ctx)
        return render(request, "blog/create_post.html", {"form": form})


class CommentCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = CommentModelForm()
        ctx = {"form": form}

        return render(request, "blog/create_comment.html", context=ctx)

    def post(self, request, *args, **kwargs):
        form = CommentModelForm(data=request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            author = request.user
            comment.author = author
            comment.save()
            ctx = {"comment": comment, "form": form}

            return render(request, "blog/create_comment.html", context=ctx)
        return render(request, "blog/create_comment.html", {"form": form})


class PostUpdateView(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            post = Post.objects.get(id=id, author=request.user)
        except Post.DoesNotExist:
            ctx = {"post_id": id, "errors": True}
            return render(request, "blog/post_update.html", context=ctx)

        form = PostModelForm(instance=post)
        ctx = {"form": form, "post": post}

        return render(request, "blog/post_update.html", context=ctx)

    def post(self, request, id, *args, **kwargs):  # normalnie aktualizujemy patch/put, ale formularz w html pozwala nam na post/get
        try:
            post = Post.objects.get(id=id, author=request.user)
        except Post.DoesNotExist:
            return HttpResponseBadRequest()
        form = PostModelForm(data=request.POST)
        if form.is_valid():
            post.content = form.cleaned_data["content"]
            post.title = form.cleaned_data["title"]
            post.save(update_fields=["content", "title"])
            ctx = {"form": form, "post": post}

            return render(request, "blog/post_update.html", context=ctx)

        ctx = {"errors": form.errors}
        return render(request, "blog/post_update.html", context=ctx)


class CommentUpdateView(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            comment = Comment.objects.get(id=id, author=request.user)
        except Comment.DoesNotExist:
            ctx = {"comment_id": id, "errors": True}
            return render(request, "blog/comment_update.html", context=ctx)

        form = CommentModelForm(instance=comment)
        ctx = {"form": form, "comment": comment}

        return render(request, "blog/comment_update.html", context=ctx)

    def post(self, request, id, *args, **kwargs):  # normalnie aktualizujemy patch/put, ale formularz w html pozwala nam na post/get
        try:
            comment = Comment.objects.get(id=id, author=request.user)
        except Comment.DoesNotExist:
            return HttpResponseBadRequest()
        form = CommentModelForm(data=request.POST)
        if form.is_valid():
            comment.post = form.cleaned_data["post"]
            comment.content = form.cleaned_data["content"]
            comment.save(update_fields=["post", "content"])
            ctx = {"form": form, "comment": comment}

            return render(request, "blog/comment_update.html", context=ctx)
        ctx = {"errors": form.errors}
        return render(request, "blog/comment_update.html", context=ctx)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            post = Post.objects.get(id=id, author=request.user)
        except Post.DoesNotExist:
            ctx = {'post_id': id, 'errors': True}
            return render(request, "blog/post_delete.html", context=ctx)
        post_title = post.title
        post_id = post.id
        post.delete()

        ctx = {"is_deleted": True, "post": {"post_title": post_title, "post_id": post_id}}

        return render(request, "blog/post_delete.html", context=ctx)


class CommentDeleteView(LoginRequiredMixin, View):
    def get(self, request, id, *args, **kwargs):
        try:
            comment = Comment.objects.get(id=id, author=request.user)
        except Comment.DoesNotExist:
            ctx = {'comment_id': id, 'errors': True}
            return render(request, "blog/comment_delete.html", context=ctx)

        comment_content = comment.content
        comment_id = comment.id
        comment.delete()

        ctx = {"is_deleted": True, "comment": {"content": comment_content, "id": comment_id}}

        return render(request, "blog/comment_delete.html", context=ctx)

my_first_project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Base title</title>
    {% endblock title %}
    {% block style %}
        <style>
            body {background-color: powderblue;}
        </style>
    {% endblock style %}
{#    {% block bootstrap %}#}
{#        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">#}
{#        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>#}
{#    {% endblock bootstrap %}#}
</head>
<body>
    <h1>No cześć!</h1>
    {% block content %}
    {% endblock content %}

</body>
</html>

my_first_project/blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block title %}
    <title>Comment detail</title>
{% endblock title %}

{% block content %}
    {% if comment %}
        <div>{{ comment.content }}</div>
    {% else %}
        <div>Comment with id: {{ comment_id }} does not exist</div>
    {% endif %}
{% endblock content %}

my_first_project/blog/templates/blog/comment_delete.html
{% extends "blog/base.html" %}

{% block title %}
    <title>Comment Deletion</title>
{% endblock title %}

{% block content %}
    {% if is_deleted %}
        <div>
        Comment {{ comment.content }} with an id {{ comment.id }} has been deleted successfully
        </div>
    {% else %}
        {% if comment_id %}
            <div>
                Comment with an id: {{ comment_id }} does not exist or you cannot access it
            </div>
        {% endif %}
    {% endif %}

    <div>
        <a href="{% url 'blog:comment_list' %}">Go to the comments list</a>
    </div>

{% endblock content %}

my_first_project/blog/templates/blog/comment_update.html
{% extends "blog/base.html" %}

{% block title %}
    <title>Update comment</title>
{% endblock title %}

{% block content %}

    <hr>
    </br>
    {% if errors %}
        <div>
        {{ errors }}
        </div>
        <div>
            Comment with an id: {{ comment_id }} does not exist or you cannot access it
        </div>
        <div>
            <a href="{% url 'blog:comment_list' %}">Go to comments list</a>
        </div>
    {% else %}
    <div>
        <span>
            Author: {{ comment.author.first_name }} {{ comment.author.last_name }} <br>
        </span>
        <span>
            Content: {{ comment.content }} <br>
        </span>
        <span>
            Post: {{ comment.post.title }} <br>
        </span>
        <span>
            Link: <a href="{% url 'blog:comment_detail' comment.id %}">Go to the comment</a>
        </span>
    </div>
    <hr>

    <form action="{% url 'blog:cbv_comment_update' comment.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
    {% endif %}
    </br>
{% endblock %}

my_first_project/blog/templates/blog/comments.html
{% extends "blog/base.html" %}

{% block title %}
<title>Comments</title>
{% endblock title %}

{% block content %}
    {% for comment in comments %}
        <div>
            <a href="{% url 'blog:cbv_comment_detail' comment.id %}">{{ comment }}</a> <a href="{% url 'blog:cbv_comment_delete' comment.id %}"> Delete </a>
        </div>
    {% endfor %}
{% endblock content %}

my_first_project/blog/templates/blog/create_comment.html
{% extends "blog/base.html" %}

{% block content %}

    <hr>
    </br>
    {% if not_authenticated %}
        <div>
            You have to be logged in to enable creating comments
        </div>
    {% else %}
    <form action="{% url 'blog:comment_create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK">
{#    <button type="submit" class="btn btn-primary">Primary</button>#}
</form>
    {% endif %}
    </br>
    <hr>

    </br>
    </br>

    {% if comment %}
        <hr>
        <div>
        {{ comment }} has been created successfully! <br>
        Post: {{ comment.post }} <br>
        Content: {{ comment.content }} <br>
        Author id: {{ comment.author.id }} <br>
        Link: <a href="{% url 'blog:comment_detail' comment.id %}">Przejdź do komentarza</a>
        </div>
        <hr>
    {% endif %}

    {% if errors %}
        <hr>
        <div>
            {% if post_id %}
                Invalid post id {{ post_id }} has been given, such post does not exist
            {% endif %}
            {% if author_id %}
                Invalid user id {{ author_id }} has been given, such author does not exist
            {% endif %}
        </div>
        <hr>
    {% endif %}
    <div>
        <a href="{% url 'blog:comment_list' %}">Wyświetl listę komentarzy</a>
    </div>

{% endblock %}

my_first_project/blog/templates/blog/create_post.html
{% extends "blog/base.html" %}

{% block content %}

    <hr>
    </br>

    <form action="{% url 'blog:cbv_post_create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK">
</form>

    </br>
    <hr>

    </br>
    </br>

    {% if post %}
        <hr>
        <div>
        {{ post }} has been created successfully! <br>
        Title: {{ post.title }} <br>
        Content: {{ post.content }} <br>
        Author: {{ post.author.id }} <br>
        Link: <a href="{% url 'blog:post_detail' post.id %}">Przejdź do posta</a>
        </div>
        <hr>
    {% endif %}

    {% if errors %}
        <hr>
        <div>
            Invalid user id {{ author_id }} has been given, such author does not exist
        </div>
        <hr>
    {% endif %}
    <div>
        <a href="{% url 'blog:post_list' %}">Wyświetl listę postów</a>
    </div>
{% endblock %}

my_first_project/blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% block title %}
<title>Post</title>
{% endblock title %}

{% block content %}
    <div>
        {{ post.title }}
    </div>
    <div>
        {{ post.content }}
    </div>

{% endblock content %}

my_first_project/blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}

{% block title %}
    <title>Post Deletion</title>
{% endblock title %}

{% block content %}
    {% if is_deleted %}
        <div>
        Post {{ post.post_title }} with an id {{ post.post_id }} has been deleted successfully
        </div>
    {% else %}
        {% if post_id %}
            <div>
                Post with an id: {{ comment_id }} does not exist or you cannot access it
            </div>
        {% endif %}
    {% endif %}

    <div>
        <a href="{% url 'blog:post_list' %}">Go to the posts list</a>
    </div>

{% endblock content %}

my_first_project/blog/templates/blog/post_update.html
{% extends "blog/base.html" %}

{% block title %}
    <title>Update post</title>
{% endblock title %}

{% block content %}

    <hr>
    </br>
    {% if errors %}
        <div>
            Post with an id: {{ post_id }} does not exist or you cannot access it
        </div>
        <div>
            <a href="{% url 'blog:post_list' %}">Go to post list</a>
        </div>
    {% else %}
    <div>
        <span>
            Author: {{ post.author.first_name }} {{ post.author.last_name }} <br>
        </span>
        <span>
            Title: {{ post.title }} <br>
        </span>
        <span>
            Content: {{ post.content }} <br>
        </span>
        <span>
            Link: <a href="{% url 'blog:post_detail' post.id %}">Go to the post</a>
        </span>
    </div>
    <hr>

    <form action="{% url 'blog:cbv_post_update' post.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
    {% endif %}
    </br>
{% endblock %}

my_first_project/blog/templates/blog/posts.html
{% extends "blog/base.html" %}
{% block title %}
<title>Posts</title>
{% endblock title %}

{% block content %}
    {% for post in posts %}
        <div>
            <a href="{% url 'blog:cbv_post_detail' post.id %}"> Post: {{ post.title }} written by: {{ post.author.username }} </a>  <a href="{% url 'blog:cbv_post_delete' post.id %}"> Usuń </a>
        </div>

    {% endfor %}
{% endblock content %}